services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=pushover://shoutrrr:ah3j24se726qrbq8q2xrag8kqxiobe@u52wpbjtdoxg19wxah39ahe5g34eqp
      - WATCHTOWER_NOTIFICATION_ONLY=true
      - WATCHTOWER_SCHEDULE=0 0 2 * * *
      - WATCHTOWER_CLEANUP=true
      - TZ=Asia/Shanghai
